// src/components/layout/footer.tsx
"use client";

import { useTranslations } from "next-intl";
import Image from "next/image";
import Link from "next/link";

export function Footer() {
  const t = useTranslations("footer");

  return (
    <footer className="border-t border-border-custom bg-surface/50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col items-center gap-8 md:flex-row md:justify-between">
          <div className="flex items-center gap-3">
            <Image
              src="/icon.png"
              alt="Keepio"
              width={32}
              height={32}
              className="rounded-lg"
            />
            <span className="font-semibold text-text-primary">Keepio</span>
          </div>

          <nav className="flex items-center gap-6">
            <Link
              href="/terms"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              {t("terms")}
            </Link>
            <Link
              href="/privacy"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              {t("privacy")}
            </Link>
            <a
              href="#contact"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              {t("contact")}
            </a>
          </nav>
        </div>

        <div className="mt-8 flex flex-col items-center gap-2 text-center text-sm text-text-muted">
          <p>
            &copy; {new Date().getFullYear()} Keepio. {t("rights")}
          </p>
          <p>
            {t("madeBy")}{" "}
            <a
              href="https://okorp.fr/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:text-accent-light transition-colors"
            >
              Okorp
            </a>
          </p>
        </div>
      </div>
    </footer>
  );
}

// components/app/Footer.vue
<script setup lang="ts">
import { useI18n } from '#imports'

const { t } = useI18n()
</script>

<template>
  <footer class="py-12 px-6 border-t border-gray-100 dark:border-gray-800 bg-white/50 dark:bg-gray-900/50">
    <div class="max-w-6xl mx-auto">
      <div class="flex flex-col md:flex-row items-center justify-between gap-6">
        <!-- Logo & Copyright -->
        <div class="flex items-center gap-3">
          <img
            src="/Icon.png"
            alt="Keepio"
            class="w-8 h-8 rounded-lg"
          />
          <div class="text-sm text-gray-500 dark:text-gray-400">
            © {{ new Date().getFullYear() }} Keepio. {{ t('rights') }}
          </div>
        </div>

        <!-- Links -->
        <nav class="flex items-center gap-6 text-sm">
          <router-link
            to="/terms"
            class="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            {{ t('gcu') }}
          </router-link>
          <router-link
            to="/privacy"
            class="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            {{ t('privacy') }}
          </router-link>
          <a
            href="mailto:contact@keepio.fr"
            class="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            {{ t('contact') }}
          </a>
        </nav>
      </div>

      <!-- Credit -->
      <div class="mt-8 pt-6 border-t border-gray-100 dark:border-gray-800 text-center">
        <p class="text-xs text-gray-400 dark:text-gray-500">
          Made with
          <span class="text-red-400">♥</span>
          by
          <a
            href="https://okorp.fr"
            target="_blank"
            rel="noopener noreferrer"
            class="hover:text-indigo-500 transition-colors"
          >
            Carolane Lefebvre
          </a>
        </p>
      </div>
    </div>
  </footer>
</template>
